print_info () {
    info title
    info underline

    info "Host" model
    info "OS" distro
    info "CPU" cpu
    info "GPU" gpu
    info "Kernel" kernel
    info "Disk" disk
    info "Memory" memory
    info "Terminal" term
    info "Resolution" resolution

    # The lines below with a '#' in front are additional info functions
    # that are disabled by default. Removing the '#' enables them and adding
    # a '#' to the start disables them again. You can add a '#' to any of the
    # lines in this function to disable their output.

    # info "Battery" battery
    # info "Font" font
    # info "Song" song
    info "Local IP" local_ip
    info "Public IP" public_ip
    info "Birthday" birthday
    info cols
}



memory_percent="on"
memory_unit="gib"
colors=(7 7 2 4 4 7)
color_blocks="off"
image_backend="chafa"
image_source="/home/chie289/Pictures/Screenshots/Untitled.png"
